apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-assistant-application
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nutrition-assistant-application
  template:
    metadata:
      labels:
        app: nutrition-assistant-application
    spec:
      containers:
        - name: nutrition-assistant-application
          image: jp.icr.io/naanamespace/nutrition-assistant-application
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP